// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhz3dsLaNozWirMwg-b_fbd1YQCbtMQHk',
    appId: '1:789432070164:web:f472f1e752091a27873701',
    messagingSenderId: '789432070164',
    projectId: 'seyhan-kaymakamligi-62f0b',
    authDomain: 'seyhan-kaymakamligi-62f0b.firebaseapp.com',
    storageBucket: 'seyhan-kaymakamligi-62f0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLG7DDGt-JmHZycywEXrIDnGSlax6a4Gg',
    appId: '1:789432070164:android:a283ad4e9266426f873701',
    messagingSenderId: '789432070164',
    projectId: 'seyhan-kaymakamligi-62f0b',
    storageBucket: 'seyhan-kaymakamligi-62f0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr-BE8s5BWMP_78_UlQWPpPx9TAmIwT4Y',
    appId: '1:789432070164:ios:f4407957598097ce873701',
    messagingSenderId: '789432070164',
    projectId: 'seyhan-kaymakamligi-62f0b',
    storageBucket: 'seyhan-kaymakamligi-62f0b.appspot.com',
    androidClientId: '789432070164-5lpgn1cd3a34vpc2rnk4b2tenenksiok.apps.googleusercontent.com',
    iosClientId: '789432070164-3dv8gtc10djk6vq7qokb1bvvlg7kp4gh.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
